version: '3.3'
services:
  dev:
    build:
      context: .
      dockerfile: Docker/ubuntu/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /cpp-dev
    tty: true
    working_dir: /cpp-dev/build
