name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
     - name: Git checkout
       uses: actions/checkout@v2
     - name: Setup python
       uses: actions/setup-python@v2
     - name: cpplint
       run: |
         pip3 install cpplint
         cd src/
         cpplint --recursive .
     - name: build
       run: |
         cd src/
         mkdir build/
         cd build/
         cmake ..
         make
