name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
     - name: Git checkout
       uses: actions/checkout@v2
     - name: Setup python
       uses: actions/setup-python@v2
     - name: Setup lint
       run: |
         pip3 install cpplint
     - name: Setup Google Test
       run: |
         sudo apt-get install libgtest-dev
         cd /usr/src/gtest
         sudo cmake CMakeLists.txt
         sudo make
         sudo cp *.a /usr/lib
         sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
         sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
         mkdir build
         cd build
         cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
         cd build make
     - name: Google Tests
       run: ctest --verbose
     - name: Cpp Lint
       run: |
         cd src/
         cpplint --recursive .
         cd ../
     - name: build
       run: |
         mkdir build
         cd build/
         cmake ..
         make
