name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
     - name: Git checkout
       uses: actions/checkout@v2
     - name: Setup python
       uses: actions/setup-python@v2
     - name: Setup lint
       run: |
         pip3 install cpplint
     - name: Setup Google Test
       run: |
         wget --q https://github.com/google/googletest/archive/release-1.12.0.tar.gz
         tar -zxvf release-1.12.0.tar.gz
         mkdir ./googletest-release-1.12.0/build
         cd /googletest-release-1.12.0/build
         cmake ..
         make
         #make install
         popd
         rm -rf buld/
     - name: build
       run: |
         mkdir build
         cd build/
         cmake ..
         make
     - name: Cpp Lint
       run: |
         cd src/
         cpplint --recursive .
         cd ../
     - name: Google Tests
       run: ctest --verbose
