name: CI

on: [push]

jobs:
  cpplint:
    runs-on: ubuntu-18.04
    steps:
     - name: Git checkout
       uses: actions/checkout@v2
     - name: Setup CppLint
       uses: actions/setup-python@v2
     - name: Install cppling
       run: pip3 install cpplint
     - run: pwd
     - name: Execute CppLint
       run: cpplint .
  build:
    runs-on: ubuntu-18.04
    steps:
     - name: Git checkout
       uses: actions/checkout@v2
     - name: build
       run: |
         pwd
         cd src/
         cd build/
         cmake ..
         make
