name: CI

on: [push]

jobs:
  cpplint:
    runs-on: ubuntu-18.04
    steps:
     - name: Git checkout
       uses: actions/checkout@v2
     - name: Setup CppLint
       uses: actions/setup-python@v2
     - run: pip3 install cpplint
     - run: cpplint --version
     - run: ls
     - run: cd .src/
     - run: ls
     - run: pwd
     - name: Execute CppLint
       run: cpplint ./hoge.cpp
  build:
    runs-on: ubuntu-18.04
    steps:
     - name: Git checkout
       uses: actions/checkout@v2
     - name: build
       run: |
         pwd
         cd src/
         mkdir build/
         cd build/
         cmake ..
         make
     - name: Execute
       run: ./hoge
